"""
Django settings for config project..

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import json
import os
import sys

import environ
import sentry_sdk
from django_log_formatter_ecs import ECSFormatter
from sentry_sdk.integrations.django import DjangoIntegration

from config.env import env

# We use django-environ but do not read a `.env` file. Locally we feed
# docker-compose an environment from a local.env file in the project root.
# In our PaaS the service's environment is supplied from Vault.
#
# NB: Some settings acquired using `env()` deliberately *do not* have defaults
# as we want to get an `ImproperlyConfigured` exception to avoid a badly
# configured deployment.
root = environ.Path(__file__) - 4

SENTRY_ENVIRONMENT = env.SENTRY_ENVIRONMENT
SENTRY_ENABLE_TRACING = env.SENTRY_ENABLE_TRACING
SENTRY_TRACES_SAMPLE_RATE = env.SENTRY_TRACES_SAMPLE_RATE

sentry_sdk.init(
    dsn=env.SENTRY_DSN,
    integrations=[DjangoIntegration()],
    environment=SENTRY_ENVIRONMENT,
    enable_tracing=SENTRY_ENABLE_TRACING,
    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
)

SITE_ROOT = root()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.DEBUG

ALLOWED_HOSTS = ["*"]

ORGANISATION_NAME = env.ORGANISATION_NAME

ORGANISATION_INITIALISM = env.ORGANISATION_INITIALISM

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_countries",
    "govuk_template_base",
    "govuk_template",
    "govuk_forms",
    "django_chunk_upload_handlers",
    "core",
    "cases",
    "users",
    "organisations",
    "contacts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_session_timeout.middleware.SessionTimeoutMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "config.middleware.APIUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.CacheControlMiddleware",
    "config.middleware.SentryContextMiddleware",
]

if env.RESTRICT_IPS:
    MIDDLEWARE.insert(0, "ip_restriction.IpWhitelister")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "..", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "govuk_template_base.context_processors.govuk_template_base",
                "config.context_processors.user_context",
                "config.context_processors.page_context",
                "config.context_processors.version_context",
                "config.context_processors.motd_context",
                "config.context_processors.add_form_errors",
                "config.context_processors.google_tag_manager",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = env.get_database_config()

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_L10N = True
USE_TZ = True

_VCAP_SERVICES = env.VCAP_SERVICES

# Redis - Trade remedies uses different redis database numbers for the Django Cache
# API:        0
# Caseworker: 1
# Public:     2
REDIS_DATABASE_NUMBER = env.REDIS_DATABASE_NUMBER
if redis := getattr(_VCAP_SERVICES, "redis", None):
    REDIS_BASE_URL = _VCAP_SERVICES.redis[0]["credentials"]["uri"]
    sentry_sdk.capture_message(f"Using VCAP redis on URL {REDIS_BASE_URL}")
else:
    REDIS_BASE_URL = env.REDIS_BASE_URL
    sentry_sdk.capture_message(f"Using local redis on URL {REDIS_BASE_URL}")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_BASE_URL}/{REDIS_DATABASE_NUMBER}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = env.SECURE_COOKIE
SESSION_EXPIRE_SECONDS = env.SESSION_LENGTH_MINUTES * 60
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = env.SESSION_EXPIRE_AFTER_LAST_ACTIVITY
CSRF_COOKIE_SECURE = env.SECURE_CSRF_COOKIE
CSRF_COOKIE_HTTPONLY = env.CSRF_COOKIE_HTTPONLY
SESSION_COOKIE_AGE = env.SESSION_LENGTH_MINUTES * 60
RESTRICT_IPS = env.RESTRICT_IPS
USE_2FA = env.USE_2FA
LOGOUT_REDIRECT_URL = "/"
FRIENDLY_DATE_FORMAT = "%-d %B %Y"
API_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

API_BASE_URL = env.API_BASE_URL
API_PREFIX = "api/v1"
API_URL = f"{API_BASE_URL}/{API_PREFIX}"
HEALTH_CHECK_TOKEN = env.HEALTH_CHECK_TOKEN
PUBLIC_BASE_URL = env.PUBLIC_BASE_URL
ENVIRONMENT_KEY = env.ENVIRONMENT_KEY
APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, "..", "static"))
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "..", "govuk_template", "static"),
    os.path.join(BASE_DIR, "..", "templates", "static"),
]

app_bucket_creds = env.get_s3_bucket_config()

AWS_ACCESS_KEY_ID = AWS_S3_ACCESS_KEY_ID = app_bucket_creds.get("storage_key")
AWS_SECRET_ACCESS_KEY = AWS_S3_SECRET_ACCESS_KEY = app_bucket_creds.get("storage_secret")
AWS_STORAGE_BUCKET_NAME = app_bucket_creds.get("bucket_name")
AWS_S3_REGION_NAME = AWS_REGION = app_bucket_creds.get("aws_region")
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ENCRYPTION = True
AWS_DEFAULT_ACL = None
# S3 client library to use
S3_CLIENT = "boto3"
# S3 Root directory name
S3_DOCUMENT_ROOT_DIRECTORY = "documents"

CLAM_AV_USERNAME = env.CLAM_AV_USERNAME
CLAM_AV_PASSWORD = env.CLAM_AV_PASSWORD
CLAM_AV_DOMAIN = env.CLAM_AV_DOMAIN

FILE_UPLOAD_HANDLERS = (
    "v2_api_client.shared.upload_handler.django_upload_handler.ExtractMetadataFileUploadHandler",
    "django_chunk_upload_handlers.clam_av.ClamAVFileUploadHandler",
    "django_chunk_upload_handlers.s3.S3FileUploadHandler",
)  # Order is important

# DEFAULT CHUNK SIZE OF 32 MB
DEFAULT_CHUNK_SIZE = env.DEFAULT_CHUNK_SIZE

# MAX FILE SIZE OF 30 MB
FILE_MAX_SIZE_BYTES = env.FILE_MAX_SIZE_BYTES

# Temporary basic auth
BASICAUTH_USERS = {
    "trade": "injury",
}

# Add the EU as a country
COUNTRIES_OVERRIDE = {
    "EU": "EU Customs Union",
}

SHOW_ENV_BANNER = env.SHOW_ENV_BANNER
ENV_NAME = env.ENV_NAME

GIT_BRANCH = env.GIT_BRANCH
GIT_COMMIT = env.GIT_COMMIT

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["stdout"],
        "level": env.ROOT_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": [
                "stdout",
            ],
            "level": env.DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": [
                "stdout",
            ],
            "level": env.DJANGO_SERVER_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": [
                "stdout",
            ],
            "level": env.DJANGO_REQUEST_LOG_LEVEL,
            "propagate": False,
        },
    },
}

ENVIRONMENT_LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "ecs_formatter": {
            "()": ECSFormatter,
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "ecs": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "ecs_formatter",
        },
    },
    "root": {
        "handlers": [
            "ecs",
        ],
        "level": env.ROOT_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": [
                "ecs",
            ],
            "level": env.DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": [
                "ecs",
            ],
            "level": env.DJANGO_SERVER_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": [
                "ecs",
            ],
            "level": env.DJANGO_REQUEST_LOG_LEVEL,
            "propagate": False,
        },
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

GOOGLE_ANALYTICS_TAG_MANAGER_ID = env.GOOGLE_ANALYTICS_TAG_MANAGER_ID

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

COUNTRIES_FIRST = ["GB"]
COUNTRIES_FIRST_BREAK = "------"

GDS_DATETIME_STRING = "%d %b %Y at %-I:%M%p"

ADMIN_DEBUG_TOOLS_ENABLED = env.ADMIN_DEBUG_TOOLS_ENABLED
