version: "2"
services:
  cli:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - .:/opt/traderemedies/caseworker
    env_file:
      - local.env
    environment:
      DEBUG: 'True'
      VCAP_SERVICES: '{"redis":[{"credentials":{"uri":"redis://localhost:6379"}}]}'
      REDIS_DATABASE_NUMBER: 1
      API_BASE_URL: http://localhost:8000
    entrypoint:
      - /opt/traderemedies/caseworker/start.sh
      - cli
    network_mode: host
