version: '2'
services:
  redis:
    image: redis:alpine
    container_name: redis-test

  code-style:
    build: .
    env_file:
      - test.env
    depends_on: 
      - redis
    entrypoint: sh -c "black /opt/traderemedies/caseworker --check && flake8"

  test-trade-remedies-caseworker:
    build: .
    env_file:
      - test.env
    depends_on:
      - redis
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 120s /opt/traderemedies/caseworker/start.sh test
