version: "3"
services:
  caseworker:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./trade_remedies_caseworker:/app/
      - ./trade_remedies_caseworker:/app/trade_remedies_client/
      - ./requirements.in:/app/requirements.in/
      - ./requirements:/app/requirements/
    env_file:
      - local.env
    command: python manage.py runserver 0.0.0.0:8000
