from django.urls import path
from cases import views as case_views

urlpatterns = [
    path("", case_views.CasesView.as_view(), name="cases"),
    path("notices/", case_views.NoticesView.as_view(), name="notices"),
    path("notice/", case_views.NoticeView.as_view(), name="notices"),
    path("notice/<uuid:notice_id>/", case_views.NoticeView.as_view(), name="notice"),
    path("create/", case_views.CaseFormView.as_view(), name="cases"),
    path("<uuid:case_id>/edit/", case_views.CaseFormView.as_view(), name="cases"),
    path("<uuid:case_id>/", case_views.CaseView.as_view(), name="cases"),
    path(
        "<uuid:case_id>/admin/", case_views.CaseAdminView.as_view(), name="case_admin"
    ),
    path(
        "<uuid:case_id>/milestones/",
        case_views.CaseMilestoneDatesView.as_view(),
        name="case_dates",
    ),
    path(
        "<uuid:case_id>/milestone/<str:milestone_key>/",
        case_views.CaseMilestoneDatesView.as_view(),
        name="case_date",
    ),
    path(
        "<uuid:organisation_id>/<uuid:case_id>/",
        case_views.CaseView.as_view(),
        name="cases",
    ),
    path("<uuid:case_id>/parties/", case_views.PartiesView.as_view(), name="cases"),
    path("<uuid:case_id>/team/", case_views.CaseTeamView.as_view(), name="case_team"),
    path("<uuid:case_id>/files/", case_views.FilesView.as_view(), name="cases"),
    path(
        "<uuid:case_id>/files/browse/",
        case_views.FileBrowseView.as_view(),
        name="cases",
    ),
    path("<uuid:case_id>/files/search/", case_views.DocumentSearchView.as_view()),
    path(
        "<uuid:case_id>/files/issue/",
        case_views.IssueFilesFormView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/files/<str:source>/",
        case_views.FilesView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/files/<str:source>/",
        case_views.FilesView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/bundles/",
        case_views.CaseBundlesView.as_view(),
        name="case_bundles",
    ),
    path(
        "<uuid:case_id>/bundle/create/",
        case_views.CaseBundleView.as_view(),
        name="case_bundle",
    ),
    path(
        "<uuid:case_id>/bundle/<uuid:bundle_id>/",
        case_views.CaseBundleView.as_view(),
        name="case_bundle",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/",
        case_views.CaseOrganisationView.as_view(),
        name="case_organisation",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/details/",
        case_views.OrganisationDetailsView.as_view(),
        name="case_organisation",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/dedupe/",
        case_views.OrganisationMatchView.as_view(),
        name="case_organisation_verify",
    ),
    # Submissions
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/",
        case_views.SubmissionView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/submission/create/",
        case_views.SubmissionCreateView.as_view(),
        name="create_submission",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/status/",
        case_views.SubmissionStatusView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/approval/",
        case_views.SubmissionApprovalView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/documents/",
        case_views.SubmissionDocumentView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/document/<uuid:document_id>/",
        case_views.SubmissionDocumentView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/notify/",
        case_views.SubmissionNotifyView.as_view(),
        name="submission_notify",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/status/notify/",
        case_views.SubmissionDeficiencyView.as_view(),
        name="submission_status_notify",
    ),
    # Client-side verify
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/verify_caserole_tasks/",
        case_views.SubmissionVerifyViewTasks.as_view(),
        name="submission_verify",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/loa/",
        case_views.SubmisisonVerifyEditLoaView.as_view(),
        name="edit_loa",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/verify_organisation/",
        case_views.SubmisisonVerifyOrganisation.as_view(),
        name="verify_organisation",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/merge_organisation/",
        case_views.SubmisisonVerifyOrganisation.as_view(enable_merge=True),
        name="verify_organisation",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/accept/",
        case_views.SubmissionVerifyAccept.as_view(),
        name="accept_organisation",
    ),
    path(
        "<uuid:case_id>/organisation/<uuid:organisation_id>/notify/",
        case_views.SubmissionVerifyNotify.as_view(),
        name="notify_organisation",
    ),
    path(
        "<uuid:case_id>/submissions/",
        case_views.SubmissionsView.as_view(),
        name="submissions",
    ),
    path(
        "<uuid:case_id>/submissions/new/",
        case_views.SubmissionsView.as_view(sub_page="new"),
        name="submissions",
    ),
    path(
        "<uuid:case_id>/submissions/draft/",
        case_views.SubmissionsView.as_view(sub_page="draft"),
        name="submissions",
    ),
    path("<uuid:case_id>/section/", case_views.NavSectionView.as_view(), name="cases"),
    path(
        "<uuid:case_id>/section/<uuid:nav_section_id>/",
        case_views.NavSectionView.as_view(),
        name="cases",
    ),
    path("<uuid:case_id>/audit", case_views.AuditView.as_view(), name="case_audit"),
    path(
        "<uuid:case_id>/audit/export/",
        case_views.CaseAuditExport.as_view(),
        name="audit_export",
    ),
    path("<uuid:case_id>/actions/", case_views.ActionsView.as_view(), name="cases"),
    path(
        "<uuid:case_id>/state/<str:state_key>/",
        case_views.StateView.as_view(),
        name="case_state",
    ),
    path(
        "<uuid:organisation_id>/<uuid:case_id>/actions/",
        case_views.ActionsView.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/actions/edit/",
        case_views.WorkflowEditor.as_view(),
        name="cases",
    ),
    path(
        "<uuid:case_id>/action/<str:action_key>/",
        case_views.ActionView.as_view(),
        name="cases",
    ),
    path("<uuid:case_id>/note/", case_views.NoteView.as_view(), name="case_note"),
    path(
        "<uuid:case_id>/note/<str:content_type>/<str:model_id>/<str:model_key>/",
        case_views.NoteView.as_view(),
        name="notes",
    ),
    path(
        "<uuid:case_id>/note/<str:content_type>/<str:model_id>/",
        case_views.NoteView.as_view(),
        name="notes",
    ),
    path(
        "<uuid:case_id>/invite/<uuid:contact_id>/as/<int:case_role_id>/",
        case_views.InviteContactView.as_view(),
        name="invite_contact_as",
    ),
    path(
        "<uuid:case_id>/invite/<uuid:contact_id>/as/<int:case_role_id>/for/<uuid:organisation_id>/",
        case_views.InviteContactView.as_view(),
        name="invite_contact_as",
    ),
    path(
        "<uuid:case_id>/invite/organisation/<uuid:organisation_id>/as/<int:case_role_id>/",
        case_views.InviteContactView.as_view(),
        name="invite_contact_as",
    ),
    path(
        "<uuid:case_id>/submission/<uuid:submission_id>/invite/<uuid:contact_id>/notify/",
        case_views.SubmissionInviteNotifyView.as_view(),
        name="invite_contact_notify",
    ),
    path(
        "<uuid:case_id>/note/<uuid:note_id>/",
        case_views.NoteView.as_view(),
        name="case_note",
    ),
    path(
        "<uuid:case_id>/public/",
        case_views.PublicFileView.as_view(),
        name="public_file",
    ),
    path(
        "<uuid:case_id>/update_parent/",
        case_views.UpdateParentView.as_view(),
        name="update_parent",
    ),
    path(
        "<uuid:case_id>/team/json/",
        case_views.CaseTeamJsonView.as_view(),
        name="case_team",
    ),
]
