version: 2
jobs:
  python_steps:
    docker:
      - image: circleci/python:3.6.10
        environment:
          DATABASE_URL: sqlite:///trade_remedies_caseworker/db.sqlite3
          DJANGO_SETTINGS_MODULE: trade_remedies_caseworker.settings.local
          DJANGO_SECRET_KEY: used_for_testing
          ALLOWED_HOSTS: "*"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - env

      - run:
          name: Run tests
          command: |
            python3 -m venv env
            . env/bin/activate          
            cd trade_remedies_caseworker
            python manage.py test
      - run:
          name: Run black
          command: |
            . env/bin/activate
            black trade_remedies_caseworker --check
      - run:
          name: Run Flake8
          command: |
            . env/bin/activate
            python -m flake8
  front_end:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Restore npm dependencies
          command: npm ci
      - run:
          name: Run prettier
          command: |
            npm run prettier
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  run_tests:
    jobs:
      - python_steps
      - front_end
