version: 2.1
jobs:
  python_steps:
    docker:
      - image: cimg/python:3.9.5
        environment:
          DATABASE_URL: sqlite:///db.sqlite3
          DJANGO_SETTINGS_MODULE: config.settings.local
          DJANGO_SECRET_KEY: used_for_testing
          ALLOWED_HOSTS: "*"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:b1:18:75:6a:a3:32:1e:12:c6:c6:61:f8:f4:a1:e7"
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests and collect fitness functions
          command: |
            . venv/bin/activate
            pytest --ignore=staticfiles -n 4 -m "not version2"
            coverage json
            codecov -t ${CODECOV_TOKEN}
            fitness-functions run . trade_remedies_caseworker
            fitness-functions publish . trade_remedies_caseworker
      - run:
          name: Push the updated READ.ME back to GitHub
          command: |
            . venv/bin/activate
            git config user.email "fitness-functions-machine-user@digital.trade.gov.uk"  # /PS-IGNORE
            git config user.name "FITNESS-FUNCTIONS MACHINE USER"  # /PS-IGNORE
            git add fitness/fitness_metrics.db
            git add fitness/fitness_metrics_graph.png
            git commit -m "[ci skip] AUTOMATED - update fitness functions"
            git push << pipeline.project.git_url >> << pipeline.git.branch >>
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            cd trade_remedies_caseworker
            black . --check
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            cd trade_remedies_caseworker
            python -m flake8
  front_end:
    docker: 
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Restore npm dependencies
          command: npm ci
      - run:
          name: Run prettier
          command: |
            npm run prettier
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          
workflows:
  version: 2
  run_tests:
    jobs:
      - python_steps
      - front_end
